services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=tangdb'
      - 'POSTGRES_PASSWORD=tangerino'
      - 'POSTGRES_USER=tangerino'
    ports:
      - '5432:5432'
